include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_return: error
    dead_code: warning

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    use_super_parameters: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
    prefer_relative_imports: true
